/** @format */

export const FETH_PAGINATION_SUCCESS = "FETH_PAGINATION_SUCCESS";
export const FETH_PAGINATION_ERROR = "FETH_PAGINATION_ERROR";

export const FETH_EPISODE_SUCCESS = "FETH_EPISODE_SUCCESS";
export const FETH_EPISODE_ERROR = "FETH_EPISODE_ERROR";
